version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - db
    #! healthcheck para esperar correctamente a la BD
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('db', 5432), timeout=2)"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    # Agregar healthcheck para PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: