version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file: .env
    #* HACER QUE LA APP WEB ESPERE A QUE LA BASE DE DATOS ESTÉ LISTA
    depends_on:
      - db

  db:
    #* USAR LA IMAGEN OFICIAL DE MYSQL
    image: postgres:13-alpine
    #* CONFIGURAR LA BASE DE DATOS CON VARIABLES DE ENTORNO
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    #* ASEGURAR QUE LOS DATOS PERSISTAN AUNQUE SE REINICIE EL CONTENEDOR
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    restart: always

#* DEFINIR EL VOLUMEN PARA LA PERSISTENCIA DE DATOS
volumes:
  postgres_data:
