from pathlib import Path

path = Path('apps/riesgos/views.py')
lines = path.read_text(encoding='utf-8').splitlines()
start = 194  # line 195 (0-based)
end = 235    # line 235 exclusive
new_block = [
    "    def _generar_tabla_riesgo(self, raw_data, parametros_manuales, is_graphable, latest_month_key):",
    "        resultados = []",
    "        map_code_to_name = {k: v for k, v in INDICADOR_MAP.items()}",
    "        map_name_to_code = {v: k for k, v in map_code_to_name.items()}",
    "        order_list = INDICADORES_GRAFICABLES_ORDER if is_graphable else INDICADORES_LIMITES_ORDER",
    "",
    "        for nombre_indicador in order_list:",
    "            ind_code = map_name_to_code.get(nombre_indicador)",
    "            if not ind_code:",
    "                continue",
    "",
    "            parametro = parametros_manuales.get(ind_code)",
    "",
    "            # Logica para obtener el valor mas reciente basado en el campo MES",
    "            datos_indicador_historicos = [",
    "                d for d in raw_data ",
    "                if INDICADOR_MAP.get(str(d.get('INDICADOR', '')).strip()) == nombre_indicador and d.get('VALOR') is not None and d.get('MES') is not None",
    "            ]",
    "",
    "            valor_actual = 0",
    "            if datos_indicador_historicos:",
    "                datos_con_fecha = []",
    "                for d in datos_indicador_historicos:",
    "                    fecha_obj, _ = parse_fecha_mes(d.get('MES'))",
    "                    if fecha_obj:",
    "                        d['parsed_date'] = fecha_obj",
    "                        datos_con_fecha.append(d)",
    "",
    "                if datos_con_fecha:",
    "                    datos_con_fecha.sort(key=lambda x: x['parsed_date'], reverse=True)",
    "                    registro_mas_reciente = datos_con_fecha[0]",
    "                    try:",
    "                        valor_actual = float(str(registro_mas_reciente['VALOR']).replace(',', '.'))",
    "                    except (ValueError, TypeError):",
    "                        valor_actual = 0",
    "",
    "                    _, month_key = parse_fecha_mes(registro_mas_reciente.get('MES'))",
    "                    if parametro and parametro.valor_override is not None and parametro.valor_override_mes:",
    "                        if month_key == parametro.valor_override_mes.upper():",
    "                            valor_actual = parametro.valor_override",
    "",
    "            elif parametro and parametro.valor_override is not None and parametro.valor_override_mes:",
    "                if parametro.valor_override_mes.upper() == latest_month_key:",
    "                    valor_actual = parametro.valor_override",
    "",
    "            apetito, tolerancia, capacidad, riesgo = None, None, None, 'N/A'",
    "            if parametro and all(p is not None for p in [parametro.apetito, parametro.tolerancia, parametro.capacidad]):",
    "                apetito, tolerancia, capacidad = parametro.apetito, parametro.tolerancia, parametro.capacidad",
    "                if valor_actual < apetito:",
    "                    riesgo = 'Bajo'",
    "                elif valor_actual < capacidad and valor_actual > apetito:",
    "                    riesgo = 'Medio'",
    "                else:",
    "                    riesgo = 'Alto'",
    "",
    "            resultados.append({",
    "                \"INDICADOR\": nombre_indicador,",
    "                \"RIESGO\": riesgo,",
    "                \"APETITO\": apetito,",
    "                \"TOLERANCIA\": tolerancia,",
    "                \"CAPACIDAD\": capacidad,",
    "            })",
    "        return resultados",
]

lines = lines[:start] + new_block + lines[end:]
path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
