# Generated by Django 5.1.4 on 2025-09-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('meta', models.CharField(max_length=100)),
                ('frecuencia_medicion', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='cumplimiento.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=20)),
                ('año', models.PositiveIntegerField()),
                ('valor', models.CharField(max_length=100)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='cumplimiento.formula')),
            ],
            options={
                'ordering': ['año', 'mes'],
                'unique_together': {('formula', 'mes', 'año')},
            },
        ),
    ]
