# Generated by Django 5.1.4 on 2025-09-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumplimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
