# Generated by Django 5.1.4 on 2025-09-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumplimiento', '0002_indicador_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='tipo_valor',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Numero', 'Número'), ('Porcentaje', 'Porcentaje')], default='Texto', max_length=20),
        ),
    ]
