# Generated by Django 5.1.4 on 2025-09-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumplimiento', '0003_formula_tipo_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='tipo_valor',
        ),
    ]
