# Generated by Django 5.1.4 on 2025-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMasUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_informe', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=150)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte Más Usado',
                'verbose_name_plural': 'Reportes Más Usados',
                'db_table': 'reporte_mas_usado',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(help_text='Nombre del reporte que se mostrará en el dashboard.', max_length=100, unique=True)),
                ('identificador', models.SlugField(help_text='Identificador único para el reporte (sin espacios ni caracteres especiales).', max_length=100, unique=True)),
                ('app_origen', models.CharField(help_text='Nombre de la app Django a la que pertenece el reporte.', max_length=50)),
                ('url_name', models.CharField(help_text='Nombre de la URL (definida en urls.py) para acceder al reporte.', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción que aparecerá en la tarjeta del dashboard.', max_length=250)),
                ('icono_fa', models.CharField(help_text="Clase del icono de Font Awesome (ej: 'fas fa-chart-line').", max_length=50)),
                ('activo', models.BooleanField(default=True, help_text="Si no está activo, se mostrará como 'Próximamente'.")),
                ('card_template', models.CharField(blank=True, help_text="Ruta a la plantilla de la tarjeta para este reporte (ej: 'gria/cards/_fondeos.html').", max_length=200, null=True)),
                ('grupos_permitidos', models.ManyToManyField(blank=True, help_text='Selecciona los grupos que tendrán acceso a este reporte.', to='auth.group')),
            ],
            options={
                'verbose_name': 'Reporte del Dashboard',
                'verbose_name_plural': 'Reportes del Dashboard',
            },
        ),
    ]
