# Generated by Django 5.1.4 on 2025-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardgria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='es_descarga',
            field=models.BooleanField(default=False, help_text='Marcar si este reporte es una descarga de archivo en lugar de una página de dashboard.'),
        ),
    ]
