# Generated by Django 5.1.4 on 2025-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardgria', '0002_reporte_es_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='orden',
            field=models.IntegerField(default=100, help_text='Orden de aparición de la tarjeta en el dashboard.'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tamaño',
            field=models.IntegerField(default=1, help_text='Tamaño de la tarjeta en el dashboard (1 o 2 columnas).'),
        ),
    ]
