# Generated by Django 5.2.4 on 2025-08-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFondeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('agencia', models.CharField(max_length=100)),
                ('ahorra_facil', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('con_semilla', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ahorra_junior', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('con_ahorrito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_ahorros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cdat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contract', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_cdat_contractual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_capt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aportes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cartera', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('capt_apo_cart', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recuado_alcaldias', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_corte_actual', models.DateField()),
                ('fecha_corte_anteior', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Seguimiento de Fondeo',
                'verbose_name_plural': 'Seguimientos de Fondeo',
                'db_table': 'fondeo',
            },
        ),
    ]
