# Generated by Django 5.1.4 on 2025-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosRiesgo',
            fields=[
                ('indicador_codigo', models.CharField(help_text="Código del indicador (ej. '1', '13', '2G') que coincide con el del SP de Oracle.", max_length=10, primary_key=True, serialize=False, unique=True)),
                ('apetito', models.FloatField(blank=True, null=True, verbose_name='Apetito')),
                ('tolerancia', models.FloatField(blank=True, null=True, verbose_name='Tolerancia')),
                ('capacidad', models.FloatField(blank=True, null=True, verbose_name='Capacidad')),
                ('valor_override', models.FloatField(blank=True, null=True, verbose_name='Valor Manual (último mes)')),
            ],
            options={
                'verbose_name': 'Parámetro de Riesgo',
                'verbose_name_plural': 'Parámetros de Riesgo',
                'ordering': ['indicador_codigo'],
            },
        ),
    ]
