# Generated by Django 5.1.4 on 2025-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosriesgo',
            name='valor_override_mes',
            field=models.CharField(blank=True, help_text='Mes para el valor de anulación (formato MES-AA, ej. OCT-23). Si está vacío, la anulación no se aplica.', max_length=10, null=True, verbose_name='Mes del Valor Manual'),
        ),
        migrations.AlterField(
            model_name='parametrosriesgo',
            name='valor_override',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Manual'),
        ),
    ]
