# Generated by Django 5.1.4 on 2026-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_parametrosriesgo_valor_override_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosRiesgoSarL',
            fields=[
                ('indicador_codigo', models.CharField(help_text="Código del indicador (ej. '1', '13', '2G') que coincide con el del SP de Oracle.", max_length=10, primary_key=True, serialize=False, unique=True)),
                ('apetito', models.FloatField(blank=True, null=True, verbose_name='Apetito')),
                ('tolerancia', models.FloatField(blank=True, null=True, verbose_name='Tolerancia')),
                ('capacidad', models.FloatField(blank=True, null=True, verbose_name='Capacidad')),
                ('valor_override', models.FloatField(blank=True, null=True, verbose_name='Valor Manual')),
                ('valor_override_mes', models.CharField(blank=True, help_text="Mes para el valor de anulación (formato MES-AA, ej. OCT-23). Si está vacío, la anulación no se aplica.", max_length=10, null=True, verbose_name='Mes del Valor Manual')),
            ],
            options={
                'verbose_name': 'Parámetro de Riesgo SARL',
                'verbose_name_plural': 'Parámetros de Riesgo SARL',
                'ordering': ['indicador_codigo'],
            },
        ),
    ]
