# Generated by Django 5.1.4 on 2026-01-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0003_parametrosriesgosarl'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosriesgosarl',
            name='orden',
            field=models.CharField(choices=[('ASC', 'Ascendente'), ('DESC', 'Descendente')], default='ASC', help_text='Define si el riesgo se calcula Ascendente o Descendente.', max_length=4),
        ),
    ]
